default:
  image: python:3.9
  before_script:
    - pip install virtualenv
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - cd fund_management_website
    - pip install -r requirements.txt
    - python3 manage.py makemigrations fund
    - python3 manage.py migrate

stages:
  - test

unit_tests:
  stage: test
  tags:
    - docker
  script:
    - python3 manage.py test

pylint:
  stage: test
  tags:
    - docker
  script:
    - pylint -d C0301 fund_management_website/fund/*.py




