# Generated by Django 3.1.10 on 2022-01-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationName', models.CharField(blank=True, max_length=200, null=True)),
                ('projectTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('CH_OSCR_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contactName', models.CharField(blank=True, max_length=200, null=True)),
                ('contactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('projectDesc', models.TextField(blank=True, max_length=300, null=True)),
                ('userGroupDesc', models.TextField(blank=True, max_length=300, null=True)),
                ('learningOpp', models.TextField(blank=True, max_length=300, null=True)),
                ('keyPartnersWork', models.TextField(blank=True, max_length=300, null=True)),
                ('projImpactClimate', models.TextField(blank=True, max_length=300, null=True)),
                ('projSupportLocBus', models.TextField(blank=True, max_length=300, null=True)),
                ('proContribution', models.TextField(blank=True, max_length=300, null=True)),
                ('length', models.IntegerField(blank=True, db_column='Length of the Project', null=True)),
                ('totalBudget', models.FloatField(blank=True, db_column='Total Budget for the Project', null=True)),
            ],
            options={
                'verbose_name_plural': 'ApplicationData',
            },
        ),
        migrations.CreateModel(
            name='BudgetProfile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.TextField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('userType', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
